### PR TITLE
fix: support expression attrbitube names in projection expressions.

### LINKED ISSUE #9: Apply ProjectionExpr to query

### PR DESCRIPTION
**Pull request by thantos**
Closes #9

When expression attribute names where only used in ProjectionExpressions, the compiler would complain. Support and enforce correct use of attribute names when using projection.

```ts
  await table
    .query({
      TableName: "TableName",
      AttributesToGet: ["attr"],
      KeyConditionExpression: "key = :val",
      FilterExpression: "key2 = :val2",
      ProjectionExpression: "#key1",
      ExpressionAttributeNames: { // <-- would not allow this, now it does
        "#key1": "",
      },
      ExpressionAttributeValues: {
        ":val": "val",
        ":val2": true,
      },
    })
    .promise();
```

### CODE REVIEW

File: src/query.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ export type QueryInput<
 > &
   ExpressionAttributeNames<KeyConditionExpression> &
   ExpressionAttributeNames<FilterExpression> &
+  ExpressionAttributeNames<ProjectionExpression> &
```
Comment (sam-goodwin) [inline src/query.ts:25]: This will also detect values, eg :val in a projection expression. I had no idea this was valid.

**Review by sam-goodwin — APPROVED** [review]

File: src/query.ts (hunk 1 above)
Comment (thantos) [reply src/query.ts:25]: Not sure what you mean, that type only detects names it seems and the docs make it seem like it can only contain `#` names.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html

Comment (sam-goodwin) [reply src/query.ts:25]: Oh my memory is wrong. Never mind, didn't think hard enough lol
